const NYT = [{
    listName: "YA Fiction",
    list_name_encoded: "hardcover-fiction",
    bestSellersDate: "2-2-2022",
    books: [{
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 1,
        rankLastWeek: 1,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 2,
        rankLastWeek: 2,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 3,
        rankLastWeek: 3,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 4,
        rankLastWeek: 4,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 5,
        rankLastWeek: 5,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 6,
        rankLastWeek: 6,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      }
    ]
  },
  {
    listName: "Mysteries",
    list_name_encoded: "mysteries",
    bestSellersDate: "2-2-2022",
    books: [{
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 1,
        rankLastWeek: 1,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 2,
        rankLastWeek: 2,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 3,
        rankLastWeek: 3,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 4,
        rankLastWeek: 4,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 5,
        rankLastWeek: 5,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 6,
        rankLastWeek: 6,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      }
    ]
  },
  {
    listName: "Thriller",
    list_name_encoded: "thriller",
    bestSellersDate: "2-2-2022",
    books: [{
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 1,
        rankLastWeek: 1,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 2,
        rankLastWeek: 2,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 3,
        rankLastWeek: 3,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 4,
        rankLastWeek: 4,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 5,
        rankLastWeek: 5,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      },
      {
        primary_isbn10: "0525559477",
        primary_isbn13: 9780525559474,
        rank: 6,
        rankLastWeek: 6,
        weeksOnList: 23,
        author: "Britney Spears",
        title: "Princess of Pop",
        description: "Nora Seed finds a library beyond the edge of the universe that contains books with multiple possibilities of the lives one could have lived.",
        publisher: "Pop Records",
        book_image: "https://storage.googleapis.com/du-prd/books/images/9780525559474.jpg",
        amazon_product_url: "https://www.amazon.com/dp/0525559477?tag=NYTBSREV-20",
      }
    ]
  }
]

const NYTcategories = ['Nora', 'Seed', 'finds', 'a', 'library', 'beyond', 'the', 'edge', 'of', 'the', 'universe', 'that', 'contains', 'books', 'with', 'multiple', 'possibilities', 'of', 'the', 'lives', 'one', 'could', 'have', 'lived'];



module.exports = {
  NYT,
  NYTcategories
}